### PR TITLE
Don't request a breaking version of postgres

### PR DESCRIPTION
**Pull request by jyn514**
Before, it would try to compile with postgres `0.17` and break with errors like this:

```
error[E0412]: cannot find type `GenericConnection` in crate `postgres`
  --> src/lib.rs:28:31
   |
28 |     connection: &'a postgres::GenericConnection,
   |                               ^^^^^^^^^^^^^^^^^ not found in `postgres`

error[E0412]: cannot find type `GenericConnection` in crate `postgres`
  --> src/lib.rs:34:42
   |
34 |     pub fn new(connection: &'a postgres::GenericConnection) -> PostgresAdapter<'a> {
   |                                          ^^^^^^^^^^^^^^^^^ not found in `postgres`

error[E0412]: cannot find type `GenericConnection` in crate `postgres`
  --> src/lib.rs:40:35
   |
40 |         connection: &'a postgres::GenericConnection,
   |                                   ^^^^^^^^^^^^^^^^^ not found in `postgres`

error[E0603]: module `transaction` is private
 --> src/lib.rs:5:15
  |
5 | use postgres::transaction::Transaction;
  |               ^^^^^^^^^^^
```

Now, it compiles using 0.15 instead.

### CODE REVIEW

**Comment by palfrey** [comment]
This one just broke me as well. Any thoughts on what we need to get this merged?

**Comment by jyn514** [comment]
I don't think this crate is maintained, I'm probably going to end up rewriting the code for this in my own project.

**Comment by SkylerLipthay** [comment]
Sorry, I was inactive in January so this slipped by me. I haven't kept up with `rust-postgres` lately but I'm guessing the right action is not to restrict this crate to be stuck to an old version of `rust-postgres`. I think the best course of action is to change `GenericConnection` to `GenericClient`. I'll look into this in the next few hours.

**Comment by SkylerLipthay** [comment]
Published `0.2.4` with this fix, which is compatible with `postgres 0.15`.

Also published `0.3.0`, which is a majorly breaking change that makes this crate compatible with `postgres 0.17`.

Thank you and sorry for the delay!

**Comment by jyn514** [comment]
Thank you for your work on this crate!
